version: '3.8'

# Services
services:
  # Nginx Service
  nginx:
    image: nginx:1.21
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/php
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  # PHP Service
  php:
    build: ./.docker/php
    working_dir: /var/www/php
    volumes:
      - ./src:/var/www/php
    depends_on:
      mariadb:
        condition: service_healthy

  # MySQL Service
  mariadb:
    build: ./.docker/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test1234
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: demo
    volumes:
      - ./.docker/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u test_user --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10

  # Redis Service
  redis:
    image: redis:latest
    # container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    depends_on:
      - php

  # PhpMyAdmin Service
  phpmyadmin:
    image: arm64v8/phpmyadmin:5.2.1
    ports:
      - 8080:80
    environment:
      PMA_HOST: mariadb
    depends_on:
      mariadb:
        condition: service_healthy

# Volumes
volumes:
  mysqldata:
  redis-data:
